### ISSUE TITLE
simpleMove for Circle2Test fails

### ISSUE THREAD

**Issue by RustyRaptor** [RustyRaptor/Programs#1]
```
Testcase: simpleMove took 0.004 sec
	FAILED
null
junit.framework.AssertionFailedError
	at edu.nmsu.cs.circles.Circle2Test.simpleMove(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by RustyRaptor** [comment]
Issue identified to be the wrong ordering of the constructor components in the super() call. Fixed.
