### ISSUE TITLE
SimpleMoveDiff fails in Circle2Test

### ISSUE THREAD

**Issue by RustyRaptor** [RustyRaptor/Programs#3]
```
Testcase: simpleMoveDiff took 0.002 sec
	FAILED
null
junit.framework.AssertionFailedError
	at edu.nmsu.cs.circles.Circle2Test.simpleMoveDiff(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

**Comment by RustyRaptor** [comment]
Issue identified as the offset being added are both OffsetX rather than X then Y respectively.
