### ISSUE TITLE
Intersect test fails for Circle2Test

### ISSUE THREAD

**Issue by RustyRaptor** [RustyRaptor/Programs#5]
```
Testcase: simpleIntersect took 0.002 sec
	FAILED
null
junit.framework.AssertionFailedError
	at edu.nmsu.cs.circles.Circle2Test.simpleIntersect(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

**Comment by RustyRaptor** [comment]
Issue found to an incorrect formula being used instead we should test. 

r1 - r2 < d < r1 + r2
