### ISSUE TITLE
simpleIntersect fails for Circle1Test

### ISSUE THREAD

**Issue by RustyRaptor** [RustyRaptor/Programs#6]
```
Testcase: simpleIntersect took 0.002 sec
	FAILED
null
junit.framework.AssertionFailedError
	at edu.nmsu.cs.circles.Circle1Test.simpleIntersect(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by RustyRaptor** [comment]
Seems to also have wrong formulat.
